// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFZNs9mZc4okxc9cwVfjRIqgblD76MYNY',
    appId: '1:341004248380:web:47e1f355c3545d6d8aaa39',
    messagingSenderId: '341004248380',
    projectId: 'aparnapod-f77a7',
    authDomain: 'aparnapod-f77a7.firebaseapp.com',
    storageBucket: 'aparnapod-f77a7.firebasestorage.app',
    measurementId: 'G-E9F503D55C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC86G13ihL_l-YJ28MdcRdvyUJQHiUbWDA',
    appId: '1:341004248380:android:69861f6ee9c8c80f8aaa39',
    messagingSenderId: '341004248380',
    projectId: 'aparnapod-f77a7',
    storageBucket: 'aparnapod-f77a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHLRGq8FGX15cDiKbygeQnRhYf1tVicII',
    appId: '1:341004248380:ios:4cef922ef45a2fb18aaa39',
    messagingSenderId: '341004248380',
    projectId: 'aparnapod-f77a7',
    storageBucket: 'aparnapod-f77a7.firebasestorage.app',
    iosBundleId: 'com.example.aparnaPod',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHLRGq8FGX15cDiKbygeQnRhYf1tVicII',
    appId: '1:341004248380:ios:4cef922ef45a2fb18aaa39',
    messagingSenderId: '341004248380',
    projectId: 'aparnapod-f77a7',
    storageBucket: 'aparnapod-f77a7.firebasestorage.app',
    iosBundleId: 'com.example.aparnaPod',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFZNs9mZc4okxc9cwVfjRIqgblD76MYNY',
    appId: '1:341004248380:web:70ec3375c8af95e48aaa39',
    messagingSenderId: '341004248380',
    projectId: 'aparnapod-f77a7',
    authDomain: 'aparnapod-f77a7.firebaseapp.com',
    storageBucket: 'aparnapod-f77a7.firebasestorage.app',
    measurementId: 'G-LWKZ180BHJ',
  );
}
